import {ArrowUpRight,Download,Mail} from 'lucide-react';
import {profileLinks} from '@/data/profile';
import {SiteHeader,SiteFooter} from '@/components/site-shell';

export default function Home(){return <><a className="skip" href="#about">Skip to introduction</a><div className="wrap"><SiteHeader/><main>
 <section className="profile-intro" id="about" aria-labelledby="intro">
  <div className="profile-copy"><div className="eyebrow">Machine learning · Computer vision · Quantitative analysis · Digital twins</div><h1 id="intro">Hi, I’m Haolin.</h1><p className="profile-lead">I build methods that turn complex data into measurable, interpretable results.</p><p>I’m a Ph.D. student at Georgia Tech. My work brings together computer vision, quantitative analysis, and reproducible Python tools to compare complex patterns and understand how they change over time.</p><p>My research applies these methods to infrastructure data. The questions behind it are broader: How do we measure agreement? How reliable are the data? And how can we tell a real change from a measurement artifact? I’m interested in bringing this way of thinking to other data-intensive research problems.</p><div className="hero-links"><a className="button" href={profileLinks.cv} download><Download size={16}/>Download my CV</a><a className="text-link" href={profileLinks.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15}/></a><a className="text-link" href="mailto:hwang972@gatech.edu"><Mail size={15}/>Email me</a></div></div>
  <aside className="portrait-card"><img className="headshot" src="/haolin-wang.png" width="486" height="470" alt="Haolin Wang"/><div className="portrait-caption"><strong>Haolin Wang</strong><span>Ph.D. student · Georgia Tech</span><span>Atlanta, Georgia</span></div></aside>
 </section>
 <section className="cv-section" id="skills"><div className="cv-section-title"><div className="eyebrow">01 / Core skills</div><h2>What I bring to a problem</h2></div><div className="cv-section-body"><div className="skill-grid">
  <article><h3>Quantitative evaluation</h3><p>Design interpretable metrics, compare methods, and investigate where results disagree. My work includes graph-based matching and rank-correlation analysis.</p></article>
  <article><h3>Computer vision & machine learning</h3><p>Work with image segmentation, feature-based registration, and model evaluation, with attention to generalization and failure cases.</p></article>
  <article><h3>Data quality & change over time</h3><p>Align repeated measurements, assess data against references, and separate meaningful changes from inconsistencies in how data were collected.</p></article>
  <article><h3>Research software & communication</h3><p>Build reproducible Python pipelines, share code and results, and explain technical methods through teaching and hands-on tools.</p></article>
 </div><p className="toolkit"><strong>Tools I work with</strong> Python · ArcGIS · SQL · MATLAB · C++ · C#</p></div></section>
 <section className="cv-section" id="work"><div className="cv-section-title"><div className="eyebrow">02 / Selected work</div><h2>What I’ve worked on</h2></div><div className="cv-section-body">
  <article className="cv-entry featured-entry"><div className="entry-kicker">Graph-based matching · Quantitative evaluation · Open source</div><h3>CRASDI: comparing the structure of crack maps</h3><p>Two crack maps can look similar while disagreeing about important details. CRASDI measures differences in crack geometry, length, width, and direction, helping explain where maps agree and where they differ.</p><p>I evaluated rank agreement with six conventional metrics on 1,405 prediction–reference pairs across nine public datasets using Spearman correlations. I also investigated unusual results linked to annotation issues and repeated prediction failures, and released Python code and reproducibility scripts.</p><div className="entry-links"><a className="text-link" href="/playground">Try the CRASDI playground <ArrowUpRight size={15}/></a><a className="text-link" href="https://github.com/THiNK327/CRASDI" target="_blank" rel="noreferrer">Code & documentation <ArrowUpRight size={15}/></a></div></article>
  <article className="cv-entry"><div className="entry-kicker">Computer vision · Temporal analysis</div><h3>Aligning images to measure change reliably</h3><p>I contributed to image registration methods that line up repeated pavement surveys. This helps separate real deterioration from apparent changes caused by shifts in the images.</p><p className="entry-citation">Related publication: “A feature-based pavement image registration method for precise pavement deterioration monitoring.” <em>Computer-Aided Civil and Infrastructure Engineering</em>, 2025. Co-authored with Z. Yang, M. Mohammadi, and Y.-C. Tsai.</p></article>
  <article className="cv-entry"><div className="entry-kicker">Simulation · Data visualization</div><h3>Mini Traffic: urban traffic simulation</h3><p>I led a team that built an urban road simulation tool in Python, C#, and SQL, with interactive data visualization. The project received third prize in the Shanghai University Student Computer Application Ability Competition.</p></article>
 </div></section>
 <section className="cv-section" id="research"><div className="cv-section-title"><div className="eyebrow">03 / In progress</div><h2>Current research</h2></div><div className="cv-section-body">
  <article className="cv-entry"><h3>Pavement crack digital twin</h3><p>I’m developing a digital twin to track pavement cracks over time. This work connects crack detection, image registration, vectorization, and comparison, with data quality and uncertainty assessment to support reliable monitoring. My proposed framework also uses more frequent camera observations to help decide when new high-resolution surveys are needed.</p></article>
  <article className="cv-entry"><h3>Automated crack sealing</h3><p>I’m studying path planning for robotic crack sealing: using crack maps to determine treatment order and movement paths, while accounting for sealing speed, travel between cracks, and operating constraints. The proposed work connects route planning with simulation and, later, robotic-arm experiments.</p></article>
 </div></section>
 <section className="cv-section" id="background"><div className="cv-section-title"><div className="eyebrow">04 / Background</div><h2>Education & experience</h2></div><div className="cv-section-body">
  <article className="cv-entry"><div className="entry-kicker">Georgia Institute of Technology · 2022–present</div><h3>Ph.D. in Civil Engineering, in progress</h3><p>Advised by Dr. Yi-chang (James) Tsai. Graduate Research Assistant in the Smart City Infrastructure Group since 2023, contributing to projects supported by NCHRP and the Georgia Department of Transportation.</p><p>Master’s degree completed at Georgia Tech in Fall 2024.</p></article>
  <article className="cv-entry"><div className="entry-kicker">Tongji University · 2017–2021</div><h3>Bachelor of Engineering in Civil Engineering</h3><p>Recognized as an Excellent Graduate in 2021. I later worked as a research intern in the Rail Transportation Construction & Management Group before joining Georgia Tech.</p></article>
 </div></section>
 <section className="cv-section" id="teaching"><div className="cv-section-title"><div className="eyebrow">05 / Teaching & mentoring</div><h2>Helping others work with data</h2></div><div className="cv-section-body"><article className="cv-entry"><p>I’ve supported courses in data analytics, AI for smart cities, and transportation safety through Python labs, assignments, and project mentoring. I also mentor student teams in Georgia Tech’s Vertically Integrated Projects program on pavement sensing and analysis.</p><p>This semester, I’m a teaching assistant for CEE 3090 Data Analytics, helping students connect analytical methods to civil engineering questions.</p><div className="award-note">2025 CEE Bill Schutz Graduate Teaching Assistant Award · Georgia Tech</div></article></div></section>
 <section className="cv-section contact-section" id="contact"><div className="cv-section-title"><div className="eyebrow">06 / Contact</div><h2>Let’s connect</h2></div><div className="cv-section-body"><p>I’d be glad to connect about computer vision, quantitative research, machine learning, or building useful tools from complex data.</p><a className="contact-email" href="mailto:hwang972@gatech.edu">hwang972@gatech.edu <ArrowUpRight size={20}/></a><div className="entry-links"><a className="text-link" href={profileLinks.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15}/></a><a className="text-link" href="https://github.com/THiNK327" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a><a className="text-link" href={profileLinks.cv} download>Full academic CV <Download size={15}/></a></div></div></section>
 </main><SiteFooter/></div></>}
